version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app   # optional, for live code updates
      - ./model:/app/model  # make sure the model file is accessible

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
    - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000/predict