# dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

# Copy requirements
COPY backend_requirements.txt .
RUN pip install --no-cache-dir -r backend_requirements.txt

# Copy backend code
COPY app/main.py ./
COPY model/ ./model/

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]